### PR TITLE
added DualBoundHistory for gurobi solver

### LINKED ISSUE #38: DualBoundHistory not read for gurobi output
When parsing a *.out file from a gurobi-run, dual bound history is empty.

[debug_gurobi.out.txt](https://github.com/GregorCH/ipet/files/1189943/debug_gurobi.out.txt)

### PR DESCRIPTION
**Pull request by leoneifler**
- resolves #38 
- added extractDualboundHistory  and helper method readBoundAndTimeDual to Solver.py
- added debug output of dual integral to Experiment.py

### CODE REVIEW

**Comment by GregorCH** [comment]
Nice. Can you add a test, too, to verify that the dual bound histories are correct in, maybe, five different cases? For this, you add a new file GurobiBoundHistoryTest to the test-directory (and add it to the test/__init__.py) that verifies the correctness for some easy cases.

**Comment by GregorCH** [comment]
Nice tests. Did you think about committing the data files to the data directory? I guess, after resolving the conflicts, this is ready to merge.

**Comment by leoneifler** [comment]
You mean the .out files that the test uses? I just used the already existing ones for gurobi and picked 2 short ones, an empty one and a long one, so they are already there.

**Comment by GregorCH** [comment]
Haha, they also looked familiar to me

**Comment by leoneifler** [comment]
Should/Can I resolve the conflicts?

**Comment by GregorCH** [comment]
Yes, I think they are on your side (Since the main master is the base)

**Comment by GregorCH** [comment]
Yes, I think they are on your side (Since the main master is the base)

**Comment by GregorCH** [comment]
@leoneifler , your new tests are failing on the test server. I cannot accept this request until this issue is resolved.

**Comment by leoneifler** [comment]
Sorry, I realized they failed but for some reason the CI details did not load when I clicked on them. Now it works and I will fix the problem.

**Pull request merged**
