### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by spoorendonk**
Updating to support python 3.7. Command line only. PyQt4 fails.

### CODE REVIEW

**Comment by GregorCH** [comment]
What a coincidence. Just today, I have had a discussion about the old dependencies. Have you tested it?

**Comment by spoorendonk** [comment]
Tests are ok except for the pandas warning.

```shell
$ python -m unittest test
/home/simon/flowty/playground/ipet/ipet/Experiment.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
..................................
----------------------------------------------------------------------
Ran 34 tests in 46.376s

OK
```

As mentioned I did not test the gui part because I could not get PyQt4 to work and porting to PyQt5 was not trivial because of `SIGNAL()` deprecation.

**Comment by GregorCH** [comment]
Here is another warning that I was told about today, this time with pandas 0.24 (this PR updates to 0.25). I am happy to merge this as all tests run through.

```
Experiment.py:246: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat(datalist).infer_objects()
```

**Comment by GregorCH** [comment]
FYI @fschloesser

**Comment by GregorCH** [comment]
The panel stuff is no longer used, anyway. It was used to build a hierarchical data frame, which is no longer necessary because of the index logic that we introduced later.

**Pull request merged**
